version: "3"
services:
  app:
    container_name: flask-elk-fluentd
    build: .
    environment:
      FLASK_APP: app
      FLASK_ENV: development
    volumes:
      - .:/app:rw
    ports:
      - "5003:5003"
    # networks:
    #   - es-net
  
  fluentd:
    build: ./fluentd
    container_name: fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    depends_on:
      - elasticsearch
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    # networks:
    #   - es-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0
    container_name: elasticsearch
    expose:
      - 9200
    ports:
      - "9200:9200"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      discovery.type: "single-node"
      node.store.allow_mmap: "false"
      xpack.security.enabled: "false"
    # networks:
    #   - es-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.0.0
    container_name: kibana
    ports:
      - "5601:5601"
    # networks:
    #   - es-net
    depends_on:
    - elasticsearch
    environment:
      discovery.type: "single-node"
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"

# networks:
#   es-net:
#     driver: bridge