
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.application.name}}
  labels:
    app: {{.Values.application.name}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{.Values.application.name}}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{.Values.application.name}}
    spec:
      containers:
      - image: {{.Values.image.repository}}
        name: flask-hello-world
        imagePullPolicy: {{.Values.image.pullPolicy}}
        resources: {}
        ports:
          - containerPort: {{.Values.application.flaskPort}} 
status: {}