version: "3"
services:
  app:
    container_name: flask-api-tests
    build: .
    environment:
      FLASK_APP: app
      FLASK_ENV: development
    volumes:
      - .:/app:rw
    ports:
      - "5002:5002"